In [1]:
# NumPy
# work efficiently with arrays and matrices in Python. 
import numpy as np

# Creating Arrays

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
# Multi Dimensional Array
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [4]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m.shape

(2, 3)

In [7]:
# Arrange Function, args- start, stop and step size
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
# Reshape to convert into list to array
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
# linspace = The linspace function is similar to arange, except we tell it how many numbers we want returned,
# and it will split up the interval accordingly.
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [11]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [12]:
# Numpy builtin function for creating array
# 1. np.ones() - return array of ones
# 2. np.zeros() - return array of zeros
# 3. np.eye() - return an array with ones on the diagonal and zeros everywhere else
# 4. np.diag() - construct a diagonal array

In [13]:
# np.ones()
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [14]:
# np.zeros()
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
# np.eye()
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
# np.diag(y)
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [18]:
# Create an array with repeate values - repeat functio
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
p = np.ones([2, 3], int)
# vstack
np.vstack([p, 2 * p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
# hstack
np.hstack([p, 2 * p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations on Numpy array

In [23]:
x + y, x * y, x ** 2

(array([5, 7, 9]), array([ 4, 10, 18]), array([1, 4, 9]))

In [24]:
x.dot(y)

32

In [25]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [26]:
# Transpose of the array
z.shape

(2, 3)

In [28]:
# Transpose the array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [29]:
z.T.shape

(3, 2)

In [31]:
# Type of element of array
z.dtype

dtype('int64')

In [33]:
# Cast to different type
# float type
z = z.astype('f')
z.dtype

dtype('float32')

In [34]:
# Maths function commonly used one

In [36]:
a = np.array([-2, -4, 1, 4])
a.sum(), a.max(), a.min(), a.mean(), a.std()

(-1, 4, -4, -0.25, 3.0310889132455352)

In [37]:
# To Find the index of a maximum or minimum value - argmax(), argmin()
a.argmax(), a.argmin()

(3, 1)

# Indexing / Slicing

In [39]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [40]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [41]:
# last 4 elements
s[-4:]

array([ 81, 100, 121, 144])

In [42]:
# :: = And here, we're starting fifth from the end to the beginning of the array and counting backwards by two. 
s [-5 :: -2]

array([64, 36, 16,  4,  0])

In [44]:
# For 2D array
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
r[2, 2]

14

In [46]:
# Now let's use colon notation to get a slice of the third row and columns three to six
r[3, 3:6]

array([21, 22, 23])

In [47]:
#We can also do something like get the first two rows and all of the columns except the last. 
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [48]:
# Select every second element from the last row
r [-1, ::2]

array([30, 32, 34])

In [49]:
# Conditional Indexing and assignment
r[r > 30]

array([31, 32, 33, 34, 35])

In [52]:
# Assignemt with some conditions all will be done on original array
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [53]:
# Copying data in Numpy
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [54]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
# See the original Array, it has been change
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [58]:
# Wish to copy the array which donot change the original array
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [63]:
r_copy[:] = 10
print(r)
print()
print(r_copy)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


# Iterating Over Arrays

In [64]:
#  First, let's create a four by three array of random numbers, from zero through nine. 
test = np.random.randint(0, 10, (4, 3))
test

array([[4, 7, 0],
       [3, 3, 0],
       [9, 4, 2],
       [6, 8, 9]])

In [65]:
# Iterate over row
for row in test:
    print(row)

[4 7 0]
[3 3 0]
[9 4 2]
[6 8 9]


In [66]:
# Use with range Function
for i in range(len(test)):
    print(test[i])

[4 7 0]
[3 3 0]
[9 4 2]
[6 8 9]


In [67]:
# Enumeration function, which gives rows and index of the row
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 7 0]
row 1 is [3 3 0]
row 2 is [9 4 2]
row 3 is [6 8 9]


In [68]:
# Iterate through two array using zip
test2 = test**2
test2

array([[16, 49,  0],
       [ 9,  9,  0],
       [81, 16,  4],
       [36, 64, 81]])

In [69]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[4 7 0] + [16 49  0] = [20 56  0]
[3 3 0] + [9 9 0] = [12 12  0]
[9 4 2] + [81 16  4] = [90 20  6]
[6 8 9] + [36 64 81] = [42 72 90]
